// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgggz9Uwd0FzUhs83PgW_bKFO7gojF2ow',
    appId: '1:595767855691:web:e7541127f9b0f84e275bce',
    messagingSenderId: '595767855691',
    projectId: 'flutter-push-notification-dam',
    authDomain: 'flutter-push-notification-dam.firebaseapp.com',
    storageBucket: 'flutter-push-notification-dam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-Xdx01l1WLYam343qrrpksehzYvgzsA',
    appId: '1:595767855691:android:0b901b5d283e0ee6275bce',
    messagingSenderId: '595767855691',
    projectId: 'flutter-push-notification-dam',
    storageBucket: 'flutter-push-notification-dam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gHTAAA6JTPRhdF5T3_-JbDi8z_L4Pmo',
    appId: '1:595767855691:ios:47c3c748243e55d1275bce',
    messagingSenderId: '595767855691',
    projectId: 'flutter-push-notification-dam',
    storageBucket: 'flutter-push-notification-dam.appspot.com',
    iosBundleId: 'com.example.pushNotificationArmenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gHTAAA6JTPRhdF5T3_-JbDi8z_L4Pmo',
    appId: '1:595767855691:ios:47c3c748243e55d1275bce',
    messagingSenderId: '595767855691',
    projectId: 'flutter-push-notification-dam',
    storageBucket: 'flutter-push-notification-dam.appspot.com',
    iosBundleId: 'com.example.pushNotificationArmenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgggz9Uwd0FzUhs83PgW_bKFO7gojF2ow',
    appId: '1:595767855691:web:e96b40cd714bda9f275bce',
    messagingSenderId: '595767855691',
    projectId: 'flutter-push-notification-dam',
    authDomain: 'flutter-push-notification-dam.firebaseapp.com',
    storageBucket: 'flutter-push-notification-dam.appspot.com',
  );
}
